# Generated by Django 3.0.7 on 2020-06-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('faq', models.BooleanField(default=False)),
            ],
        ),
    ]
