# Generated by Django 3.0.7 on 2020-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='about_us',
            new_name='about_app',
        ),
    ]
