# Generated by Django 3.0.7 on 2020-06-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_panel', '0002_auto_20200621_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='test_panel.Question'),
        ),
    ]
