# Generated by Django 3.0.7 on 2020-06-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_panel', '0003_auto_20200621_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='passed_the_test',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
