# Generated by Django 3.0.7 on 2020-06-22 19:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_auto_20200623_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
