# Generated by Django 3.0.7 on 2020-06-22 20:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_auto_20200623_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contents'),
        ),
    ]
